version: "3.8"

networks:
  mc-server:

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/cyrof/mc-test:/data
    restart: on-failure:3
    networks:
      - mc-server
    

  ngrok: 
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=<ngrok authtoken>
    command: 'tcp minecraft:25565'
    ports:
      - 4040:4040
    networks:
      - mc-server
